export enum AdvanceTypes {
  Tools = 'Narzędzia',
  Hunting = 'Łowy',
  Fishing = 'Łowienie',
  Health = 'Zdrowie',
  Clothing = 'Ubrania',
  Fire = 'Ogień',
  Gathering = 'Zbieractwo',
  Religion = 'Religia',
  Shelter = 'Schronienie',
  Prey = 'Polowanie',
  Art = 'Sztuka',
}

interface InitAdvance {
  label: string;
  type: string;
}

export const initAdvancesList: InitAdvance[] = [
  { label: 'Zioła lecznicze', type: AdvanceTypes.Health },
  { label: 'Prymitywna chirurgia', type: AdvanceTypes.Health },
  { label: 'Położne', type: AdvanceTypes.Health },
  { label: 'Opatrywanie ran', type: AdvanceTypes.Health },
  { label: 'Składanie złamań', type: AdvanceTypes.Health },
  { label: 'Zielarz', type: AdvanceTypes.Health },
  { label: 'Udomownie wilka', type: AdvanceTypes.Hunting },
  { label: 'Łuk i strzały', type: AdvanceTypes.Hunting },
  { label: 'Włócznia', type: AdvanceTypes.Hunting },
  { label: 'Współpraca myśliwych', type: AdvanceTypes.Hunting },
  { label: 'Atlatl rzucający włócznie', type: AdvanceTypes.Hunting },
  { label: 'Pułapki na zwierzęta', type: AdvanceTypes.Hunting },
  { label: 'Sieci', type: AdvanceTypes.Hunting },
  { label: 'Nomadyczny styl życia', type: AdvanceTypes.Hunting },
  { label: 'Polowanie na konie', type: AdvanceTypes.Prey },
  { label: 'Polowanie na mamuty', type: AdvanceTypes.Prey },
  { label: 'Polowanie na żubry', type: AdvanceTypes.Prey },
  { label: 'Polowanie na niedźwiedzie', type: AdvanceTypes.Prey },
  { label: 'Polowanie na renifery', type: AdvanceTypes.Prey },
  { label: 'Polowanie na jelenie', type: AdvanceTypes.Prey },
  { label: 'Polowanie na ptaki', type: AdvanceTypes.Prey },
  { label: 'Polowanie na zające', type: AdvanceTypes.Prey },
  { label: 'Drewniane trzonki i uchwyty', type: AdvanceTypes.Tools },
  { label: 'Użycie żywicy', type: AdvanceTypes.Tools },
  { label: 'Dłuta i szydła', type: AdvanceTypes.Tools },
  { label: 'Wytaczarki i wiertarki', type: AdvanceTypes.Tools },
  { label: 'Kamienne noże i ostrza', type: AdvanceTypes.Tools },
  { label: 'Kamienne siekiery i topory', type: AdvanceTypes.Tools },
  { label: 'Kamienne piły i igły', type: AdvanceTypes.Tools },
  { label: 'Moździerze i tłuczki', type: AdvanceTypes.Tools },
  { label: 'Lampy olejowe', type: AdvanceTypes.Fire },
  { label: 'Rozpalanie ognia', type: AdvanceTypes.Fire },
  { label: 'Wędzone mięso', type: AdvanceTypes.Fire },
  { label: 'Ciepłe palenisko', type: AdvanceTypes.Fire },
  { label: 'Rozpalanie krzemieniem', type: AdvanceTypes.Fire },
  { label: 'Rozpalanie cięciwą', type: AdvanceTypes.Fire },
  { label: 'Szycie i krawiectwo', type: AdvanceTypes.Clothing },
  { label: 'Futra i skóry', type: AdvanceTypes.Clothing },
  { label: 'Wyprawianie skór', type: AdvanceTypes.Clothing },
  { label: 'Włókna roślinne', type: AdvanceTypes.Clothing },
  { label: 'Igły z kości i nici z ścięgien', type: AdvanceTypes.Clothing },
  { label: 'Obuwie', type: AdvanceTypes.Clothing },
  { label: 'Zbieranie ziaren i orzechów', type: AdvanceTypes.Gathering },
  { label: 'Zbieranie owoców i warzyw', type: AdvanceTypes.Gathering },
  { label: 'Zbieranie korzeni i bulw', type: AdvanceTypes.Gathering },
  { label: 'Zbieranie skorupiaków', type: AdvanceTypes.Gathering },
  { label: 'Wiązanie koszy', type: AdvanceTypes.Gathering },
  { label: 'Motyki i sierpy', type: AdvanceTypes.Gathering },
  { label: 'Zamieszkiwanie jaskiń', type: AdvanceTypes.Shelter },
  { label: 'Namioty z skór', type: AdvanceTypes.Shelter },
  { label: 'Chaty ze strzechą', type: AdvanceTypes.Shelter },
  { label: 'Domy ziemianki', type: AdvanceTypes.Shelter },
  { label: 'Wiaty', type: AdvanceTypes.Shelter },
  { label: 'Chaty z cegieł błotnych', type: AdvanceTypes.Shelter },
  { label: 'Szamanizm', type: AdvanceTypes.Religion },
  { label: 'Rytuały myśliwych', type: AdvanceTypes.Religion },
  { label: 'Ceremonie pogrzebowe', type: AdvanceTypes.Religion },
  { label: 'Kult płodności', type: AdvanceTypes.Religion },
  { label: 'Magia i czary', type: AdvanceTypes.Religion },
  { label: 'Kalendarz księżycowy', type: AdvanceTypes.Religion },
  { label: 'Maski i biżuteria', type: AdvanceTypes.Art },
  { label: 'Muzyka i taniec', type: AdvanceTypes.Art },
  { label: 'Malowanie jaskiń', type: AdvanceTypes.Art },
  { label: 'Piktogramy', type: AdvanceTypes.Art },
  { label: 'Rzeźbione figurki', type: AdvanceTypes.Art },
  { label: 'Garncarstwo', type: AdvanceTypes.Art },
  { label: 'Harpuny z kości', type: AdvanceTypes.Fishing },
  { label: 'Sieci', type: AdvanceTypes.Fishing },
  { label: 'Dłubane kajaki', type: AdvanceTypes.Fishing },
  { label: 'Tratwy z trzciny', type: AdvanceTypes.Fishing },
  { label: 'Haczyki', type: AdvanceTypes.Fishing },
  { label: 'Pułapki na ryby', type: AdvanceTypes.Fishing },
];
